language: python

install:
- pip install sphinx_rtd_theme mock

script:
- sphinx-build -Wv source docs/html

deploy:
  - provider: pages
    skip_cleanup: true
    keep-history: false
    github_token: $GITHUB_TOKEN
    local_dir: docs/html
    on:
      branch: master
    
    
    
